spring.application.name=AudioTranscribe
server.port=8081
spring.ai.openai.api-key=085e9409fae44ea3b8fe193e7f019fc8
spring.ai.openai.audio.transcription.base-url=https://api.openai.com
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json
